/** Domain contracts deliberately contain no framework, database, or hardware imports. */
export type Provenance = 'SIMULATED' | 'MEASURED' | 'FORECAST' | 'ESTIMATED' | 'DERIVED' | 'MANUAL' | 'REFERENCE';
export type Quality = 'valid' | 'stale' | 'outlier' | 'conflict' | 'missing';
export interface Datum<T = number> { value: T; unit: string; provenance: Provenance; sourceId: string; measuredAt: string; quality: Quality; }
export interface WeatherInput { date: string; latitudeDeg: number; elevationM: number; temperatureMaxC: number; temperatureMinC: number; relativeHumidityMaxPct: number; relativeHumidityMinPct: number; windSpeedMps: number; solarRadiationMjM2Day: number; }
export interface AgronomyParameters { version: string; fieldAreaM2: number; fieldCapacity: number; wiltingPoint: number; rootDepthM: number; evaporationDepthM: number; readilyEvaporableWaterMm: number; cropHeightM: number; kcb: number; depletionFraction: number; applicationEfficiency: number; wettedFraction: number; earlyWarningFraction: number; actionDepletionFraction: number; targetDepletionFraction: number; capillaryRiseMm: number; }
export interface AgronomyInput { weather: WeatherInput; parameters: AgronomyParameters; rootZoneDepletionMm: number; surfaceDepletionMm: number; observedRainMm: number; runoffMm?: number; netIrrigationMm?: number; surfaceWetting?: 'drip' | 'rain'; }
export interface EtoResult { etoMm: number; dayOfYear: number; meanTemperatureC: number; saturationVaporPressureKpa: number; actualVaporPressureKpa: number; vaporPressureDeficitKpa: number; slopeKpaC: number; atmosphericPressureKpa: number; psychrometricConstantKpaC: number; extraterrestrialRadiationMjM2Day: number; clearSkyRadiationMjM2Day: number; netShortwaveRadiationMjM2Day: number; netLongwaveRadiationMjM2Day: number; netRadiationMjM2Day: number; }
export interface AgronomyResult extends EtoResult { engineVersion: string; parameterVersion: string; input: AgronomyInput; kcb: number; kcmax: number; canopyFraction: number; exposedWettedFraction: number; tewMm: number; kr: number; ke: number; ks: number; potentialEtcMm: number; etcMm: number; evaporationMm: number; tawMm: number; adjustedDepletionFraction: number; rawMm: number; startingDepletionMm: number; rootZoneDepletionMm: number; surfaceDepletionMm: number; deepPercolationMm: number; surfaceDrainageMm: number; targetDepletionMm: number; netDepthMm: number; grossDepthMm: number; netVolumeLiters: number; grossVolumeLiters: number; irrigationRequired: boolean; }
export type ScenarioId = 'normal-hot-day' | 'rain-succeeds' | 'rain-fails' | 'rain-underperforms' | 'unexpected-storm' | 'high-flow' | 'low-flow' | 'low-pressure' | 'sensor-offline' | 'sensor-outlier' | 'valve-failure' | 'telemetry-conflict';
export interface ScenarioDefinition { id: ScenarioId; name: string; description: string; }
export type AlertType = 'HIGH_FLOW' | 'LOW_FLOW' | 'LOW_PRESSURE' | 'SENSOR_OFFLINE' | 'SENSOR_OUTLIER' | 'TELEMETRY_CONFLICT' | 'RAIN_UNDER_FORECAST' | 'UNEXPECTED_RAIN' | 'ROOT_ZONE_NEAR_STRESS' | 'ROOT_ZONE_STRESS' | 'VALVE_FAILURE' | 'PUMP_FAILURE';
export interface FieldAlert { id: string; type: AlertType; severity: 'info' | 'warning' | 'critical'; title: string; message: string; detectedAt: string; status: 'active' | 'resolved'; evidence: string; possibleCauses: string[]; resolution?: string; deviceId?: string; }
export interface IrrigationZone { id: 'A' | 'B' | 'C' | 'D'; name: string; areaM2: number; nominalFlowM3h: number; flowM3h: number; pressureBar: number; targetVolumeLiters: number; deliveredVolumeLiters: number; estimatedRuntimeMinutes: number; state: 'idle' | 'opening' | 'running' | 'paused' | 'completed' | 'stopped' | 'fault'; valveState: 'CLOSED' | 'OPENING' | 'OPEN' | 'CLOSING' | 'FAILED'; }
export interface DeviceReading { id: string; name: string; kind: 'weather' | 'rain' | 'soil' | 'flow' | 'pressure' | 'valve' | 'pump'; zoneId?: string; depthCm?: number; status: 'online' | 'offline' | 'warning'; datum: Datum<number | string>; lastSeen: string; }
export interface Recommendation { status: 'irrigate' | 'wait-for-rain' | 'monitor' | 'blocked' | 'irrigating' | 'complete'; title: string; reason: string; netDepthMm: number; grossDepthMm: number; netVolumeLiters: number; grossVolumeLiters: number; estimatedRuntimeMinutes: number; perZoneRuntimeMinutes: number; targetDepletionMm: number; confidence: 'Complete' | 'Moderate' | 'Degraded'; engineVersion: string; parameterVersion: string; calculatedAt: string; projectedNoRainDepletionMm: number; }
export interface HistoryPoint { at: string; depletionMm: number; rawMm: number; etoMm: number; etcMm: number; rainfallMm: number; deliveredVolumeLiters: number; soilMoisture20Pct: number; soilMoisture40Pct: number; soilMoisture60Pct: number; flowM3h: number; pressureBar: number; }
export interface SimulationEvent { id: string; at: string; type: string; message: string; }
export interface SimulationState { schemaVersion: 1; id: string; scenarioId: ScenarioId; clock: string; version: number; elapsedSeconds: number; status: 'idle' | 'running' | 'paused' | 'stopped' | 'completed'; field: { id: string; farmName: string; name: string; region: string; crop: string; plantingDate: string; areaM2: number; widthM: number; lengthM: number; growthStage: string; daysAfterPlanting: number; rootDepthM: number; }; weather: WeatherInput; parameters: AgronomyParameters; calculation: AgronomyResult; rain: { forecastMm: number; observedMm: number; scenarioReceivedMm: number; windowStart: string; windowEnd: string; probabilityPct: number; reconciled: boolean; eventOpen: boolean; lastRainAt: string | null; eventQuietMinutes: number; }; soil: { rootZoneDepletionMm: number; surfaceDepletionMm: number; fieldCapacity: number; wiltingPoint: number; tawMm: number; rawMm: number; moisture20Pct: number; moisture40Pct: number; moisture60Pct: number; deepPercolationMm: number; }; zones: IrrigationZone[]; devices: DeviceReading[]; alerts: FieldAlert[]; recommendation: Recommendation; history: HistoryPoint[]; events: SimulationEvent[]; control: { activeZoneIndex: number; activeZoneSeconds: number; pumpState: 'OFF' | 'STARTING' | 'ON' | 'FAILED'; pauseReason: string | null; runStartedAt: string | null; runTargetLiters: number; deliveredVolumeLiters: number; rainPaused: boolean; }; accounting: { day: string; appliedEtMm: number; observedRainMm: number; netDeliveryMm: number; historyAt: string; }; }
export interface WeatherProvider { read(at: string): Promise<Datum<WeatherInput>>; }
/** Optional for persisted schema-1 compatibility; absent means the configured drip pattern. */
export interface SimulationState { surfaceWetting?: 'drip' | 'rain'; eventSequence?: number; rainWindowObservedMm?: number; simulationConfiguration?: { version: string; policy: Record<string, unknown>; deviceQualityPolicy: Record<string, unknown>; dripProfile: Record<string, unknown>; cropStageDays: number[]; }; }
export interface ZoneSoilConfiguration { version: string; source: string; zones: Array<{ zoneId: IrrigationZone['id']; parameters: AgronomyParameters; rootZoneDepletionMm: number; surfaceDepletionMm: number; }>; }
export interface ZoneSoilLedger { zoneId: IrrigationZone['id']; parameters: AgronomyParameters; rootZoneDepletionMm: number; surfaceDepletionMm: number; calculation: AgronomyResult; surfaceWetting: 'drip' | 'rain'; accounting: { day: string; appliedEtMm: number; observedRainMm: number; netDeliveryMm: number; deepPercolationMm: number; }; }
export interface SimulationState { soilModel?: { mode: 'zone-specific'; version: string; source: string; configuredAt: string; zones: ZoneSoilLedger[]; }; }
export interface AgronomyResult { aggregation?: 'area-weighted-zone-summary'; zoneCalculations?: Record<string, AgronomyResult>; }
export interface Recommendation { zoneRecommendations?: Array<{ zoneId: string; recommendation: Recommendation }>; }
export interface RainfallProvider { read(at: string): Promise<Datum>; }
export interface SoilMoistureProvider { read(depthCm: number, at: string): Promise<Datum>; }
export interface FlowProvider { read(zoneId: string, at: string): Promise<Datum>; }
export interface PressureProvider { read(zoneId: string, at: string): Promise<Datum>; }
export interface DeviceHealthProvider { read(deviceId: string, at: string): Promise<Datum<string>>; }
export interface IrrigationController { command(command: { id: string; zoneId: string; desiredState: 'OPEN' | 'CLOSED'; issuedAt: string; deadline: string }): Promise<{ commandId: string; acknowledged: boolean; observedState: 'OPEN' | 'CLOSED' | 'UNKNOWN' }>; }
