export const accessCopy = {
  title: 'People & permissions',
  description: 'Invite a colleague or grant access to an existing account. Every access change is recorded in the audit log.',
  inviteTitle: 'Add an administrator',
  inviteHint: 'New accounts receive a secure email invitation to choose their own password. Existing accounts keep their sign-in credentials.',
  email: 'Email address',
  role: 'Access level',
  owner: 'Owner',
  admin: 'Administrator',
  farmer: 'No administrator access',
  manageAdmins: 'Manage other administrators',
  ownerProtection: 'Owners control ownership. The initial owner is permanently protected; ordinary administrators cannot change any owner account.',
  selfProtection: 'You cannot change your own access from this panel.',
  protectedOwner: 'Protected initial owner',
  disabled: 'Sign-in access disabled',
  invite: 'Invite / add administrator',
  invitationSaved: 'Access request recorded. New users receive an invitation email.',
  saved: 'Access updated.',
  unavailable: 'Access management is unavailable. Please try again.',
  forbidden: 'Your account needs permission to manage administrators. An owner can grant this permission.',
  noUsers: 'No administration accounts are available.',
  save: 'Save access',
  cancel: 'Cancel',
  edit: 'Edit access',
  refresh: 'Refresh',
  pending: 'Invitation history',
  status: 'Status',
  permissions: 'Administrative permissions',
  permissionsHint: 'An administrator can grant only permissions they already hold. Owners have all permissions.',
  operationalPermissions: {
    'simulation.manage': 'Manage simulation and irrigation',
    'devices.manage': 'Manage devices and credentials',
    'parameters.manage': 'Manage parameter versions',
    'audit.read': 'Read audit records',
  },
} as const;

export const authCopy = {
  eyebrow: 'ACCOUNT SETUP',
  title: 'Make your account your own.',
  description: 'Choose a password for your invited account. Access is assigned by an authorized administrator.',
  loading: 'Verifying your secure link…',
  invalid: 'This link is missing, expired, or already used. Ask your administrator for a new invitation, or use the documented trusted recovery procedure.',
  unavailable: 'The account service is unavailable. Please try again.',
  saveFailed: 'The password could not be saved. Use a unique password of at least 12 characters, or request a fresh secure link.',
  password: 'New password',
  confirmPassword: 'Confirm password',
  passwordHint: 'Use at least 12 characters and a unique password.',
  mismatch: 'The passwords do not match.',
  save: 'Save password',
  saving: 'Saving…',
  saved: 'Your password is saved. You can now sign in with your assigned access.',
  signIn: 'Continue to sign in',
} as const;
