/** English interface catalogue. Technical identifiers, units and versioned domain messages stay with their owners. */
export const copy = {
  system: {
    interruptedTitle: "Something interrupted the connection.",
    interruptedDescription: "Your saved field data is safe. Try loading this view again.",
    retry: "Try again",
    notFoundTitle: "This path doesn’t lead to a field.",
    notFoundDescription: "The page may have moved.",
    backToToday: "Back to Today",
    loadingField: "Loading field information",
  },
  admin: {
    parameterNotesExample: "Document each reference or simulation assumption",
    signInFailed: "Sign-in failed.",
    connectionUnavailable: "Connection unavailable.",
    administration: "BARAKA AGRO ADMINISTRATION",
    administratorAccessRequired: "Administrator access required.",
    welcomeBack: "Welcome back.",
    thisAccountDoesNotHaveAnAdministratorRole: "This account does not have an administrator role. Sign in with an authorized account.",
    signInToManageTheSharedFieldSimulation: "Sign in to manage the shared field simulation and integration tools.",
    email: "Email",
    password: "Password",
    signingIn: "Signing in…",
    signIn: "Sign in",
    accessIsProvisionedThroughAPrivilegedServerDatabase: "Access is provisioned through a privileged server/database bootstrap. Accounts cannot assign themselves an administrator role.",
    simulationLab: "Simulation Lab",
    deviceIntegration: "Device Integration",
    commissioning: "Commissioning",
    calculationInspector: "Calculation Inspector",
    telemetry: "Telemetry",
    agronomyParameters: "Agronomy Parameters",
    alerts: "Alerts",
    auditLogs: "Audit Logs",
    teamAndAccess: "Team & Access",
    noNormalizedReading: "No simulated reading for this identity. Inspect incoming telemetry below.",
    deviceActionSuffix: " device",
    unableToLoadAdministration: "Unable to load administration.",
    actionFailed: "Action failed.",
    theActionFailed: "The action failed.",
    deviceConfigurationSaved: "Device configuration saved.",
    deviceRegistered: "Device registered.",
    newImmutableParameterVersionSaved: "New immutable parameter version saved.",
    engineeringWorkspace: "ENGINEERING WORKSPACE",
    aClearerViewOfTheSystem: "A clearer view of the system.",
    signedInAs: (value1: string | number) => "Signed in as " + value1 + "",
    signOut: "Sign out",
    exitYourLocalPreviewBeforeChangingTheShared: "Exit your local preview before changing the shared simulation.",
    exitPreview: "Exit preview",
    adminSections: "Admin sections",
    deterministicScenarioControl: "Deterministic scenario control",
    simulationScenario: "Simulation scenario",
    scenarioResetToItsInitialCheckpoint: "Scenario reset to its initial checkpoint.",
    loadReset: "Load / reset",
    simulationSpeed: "Simulation speed",
    speed: "× speed",
    pause: "Pause",
    run: "Run",
    step1Minute: "Step 1 minute",
    simulationClock: "Simulation clock",
    currentDepletion: "Current depletion",
    areaWeightedCurrentDepletion: "Area-weighted depletion",
    deliveredIrrigation: "Delivered irrigation",
    dataCompleteness: "Data completeness",
    runControlsTheScenarioClockStartIrrigationFrom: "Run controls the scenario clock. Start irrigation from the Irrigation page’s administrator controls. Advancement continues across navigation while this session remains open.",
    currentRecommendation: "Current recommendation",
    grossDelivery: "Gross delivery",
    stateVersion: "State version",
    engine: "Engine",
    scenarioEvents: "Scenario events",
    registeredDeviceIdentities: "Registered device identities",
    registerDevice: "Register device",
    device: "Device",
    identity: "Identity",
    mode: "Mode",
    binding: "Binding",
    inspect: "Inspect",
    zone: (value1: string | number) => "Zone " + value1 + "",
    field: "Field",
    integrationDetail: (value1: string | number) => "" + value1 + " · integration detail",
    registeredConfiguration: "Registered configuration",
    latestNormalizedReading: "Latest normalized reading",
    editConfiguration: "Edit configuration",
    issueDeviceCredential: "Issue device credential",
    deviceDisabled: "Device disabled.",
    deviceEnabled: "Device enabled.",
    disable: "Disable",
    enable: "Enable",
    copyThisCredentialNowItIsShownOnly: "Copy this credential now. It is shown only once.",
    credentialCopied: "Credential copied.",
    copy: "Copy",
    commissioningPreparation: "Commissioning preparation",
    allCurrentChecksAreSimulatedPhysicalCalibrationRemains: "All current checks are simulated. Physical calibration remains pending until hardware is connected.",
    commissioningDevice: "Commissioning device",
    simulatedCommissioningChecksRecordedNoPhysicalTestWas: "Simulated commissioning checks recorded. No physical test was performed.",
    runSimulatedChecks: "Run simulated checks",
    reproducibleCalculationSnapshots: "Reproducible calculation snapshots",
    calculationSnapshot: "Calculation snapshot",
    snapshotsPreserveRawInputsNormalizedValuesIntermediateCalculations: "Snapshots preserve raw inputs, normalized values, intermediate calculations, versions, and provenance.",
    receivedTelemetry: "Received telemetry",
    refresh: "Refresh",
    versionedParameterSets: "Versioned parameter sets",
    newVersion: "New version",
    kind: "Kind",
    version: "Version",
    name: "Name",
    sourceTitle: "Source title",
    sourceOrganization: "Source organization",
    assumptionsNotes: "Assumptions / notes",
    parametersJson: "Parameters (JSON)",
    saveNewImmutableVersion: "Save new immutable version",
    savingAReferenceVersionDoesNotSilentlyAlter: "Saving a reference version does not silently alter active or historical calculations.",
    evidenceAndPossibleCauses: "Evidence and possible causes",
    authoritativeMutationAudit: "Authoritative mutation audit",
  },
  appShell: {
    mainNavigation: "Main navigation",
    skipToContent: "Skip to content",
    yourWorkspace: "YOUR WORKSPACE",
    aLittleMoreCare: "A little more care.",
    aLittleLessWater: "A little less water.",
    betterDecisionsFor: "Better decisions for",
    everyGrowingDay: "every growing day.",
    tashkentDemoFarm: "Tashkent Demo Farm",
    tashkentUzbekistan: "Tashkent, Uzbekistan",
    northPotatoField: "North Potato Field",
    tashkentRegion: " Tashkent Region ",
    text10Ha: " 1.0 ha",
    realCalculationsSimulatedReadings: "Real calculations. Simulated readings.",
    understood: "Understood",
    publicFarmView: "Public farm view",
    yourIrrigationPreview: "Your irrigation preview",
    sessionOnly60Speed: " · Session only · 60× speed",
    exitPreview: "Exit preview ",
    authoritativeSimulationRunningAt: "Authoritative simulation running at ",
    tashkentTime: " Tashkent time",
    growingWithIntention: " Growing with intention.",
    fao56BasedMethodology: "FAO-56-based methodology ",
  },
  charts: {
    mmPerDay: "mm / day",
    sevenDayForecastTodaySEstimatedCropWater: (value1: string | number) => "Seven-day forecast. Today’s estimated crop water use is " + value1 + " millimeters. Forecast rain remains separate from observed water.",
    plannedGrossIrrigation: "Planned gross irrigation",
    forecastRain: "Forecast rain",
    cropWaterUse: "Crop water use",
    plannedIrrigation: "Planned irrigation",
    soilMoistureAt2040And60Centimeters: (value1: string | number) => "Soil moisture at 20, 40, and 60 centimeters. Current shallow reading " + value1 + " percent.",
    text20Cm: "20 cm",
    text40Cm: "40 cm",
    text60Cm: "60 cm",
    text60CmBelowRootZone: "60 cm · below root zone",
    rootZoneDepletionHistoryComparedWithTheReadily: "Root-zone depletion history compared with the readily available water threshold",
    depletionMm: "Depletion (mm)",
    rawMm: "RAW (mm)",
    referenceEvapotranspirationAndCropEvapotranspirationHistory: "Reference evapotranspiration and crop evapotranspiration history",
    referenceEtMm: "Reference ET₀ (mm)",
    cropEtMm: "Crop ET (mm)",
  },
  deviceCredentials: {
    credentialMetadataUnavailable: "Credential metadata unavailable.",
    revocationFailed: "Revocation failed.",
    credentialLifecycle: "Credential lifecycle",
    prefix: "Prefix",
    created: "Created",
    lastUsed: "Last used",
    status: "Status",
    action: "Action",
    never: "Never",
    revoked: "Revoked",
    expired: "Expired",
    active: "Active",
    revoke: "Revoke",
    noCredentialsIssuedForThisDevice: "No credentials issued for this device.",
  },
  deviceIdentityForm: {
    deviceId: "Device ID",
    name: "Name",
    kind: "Kind",
    sourceMode: "Source mode",
    assignment: "Assignment",
    wholeField: "Whole field",
    zone: "Zone ",
    configurationJson: "Configuration (JSON)",
    recordAdapterSettingsFirmwareAndCalibrationMetadataHere: "Record adapter settings, firmware and calibration metadata here. Store device credentials through the credential controls.",
    saveConfiguration: "Save configuration",
    saveIdentity: "Save identity",
    cancel: "Cancel",
  },
  explanation: {
    weatherSetsTheStartingPoint: "Weather sets the starting point",
    simulatedWeatherFao56Equations640: "Simulated weather · FAO-56 equations 6–40",
    temperatureRange: "Temperature range",
    relativeHumidity: "Relative humidity",
    windAt2M: "Wind at 2 m",
    solarRadiation: "Solar radiation",
    referenceEt: "Reference ET₀",
    potatoInItsGrowingSeason: "Potato, in its growing season",
    referenceParameters: (value1: string | number) => "Reference parameters · " + value1 + "",
    growthStage: "Growth stage",
    basalCoefficientKcb: "Basal coefficient Kcb",
    evaporationCoefficientKe: "Evaporation coefficient Ke",
    waterStressCoefficientKs: "Water stress coefficient Ks",
    cropWaterUse: "Crop water use",
    etcKsKcbKeEt: "ETc = (Ks × Kcb + Ke) × ET₀",
    waterStoredInTheRootZone: "Water stored in the root zone",
    derivedFieldLevelWaterBalance: "Derived · field-level water balance",
    derivedZoneSoilSummary: "Derived · area-weighted summary of configured zone water balances",
    rootDepth: "Root depth",
    totalAvailableWater: "Total available water",
    readilyAvailableWater: "Readily available water",
    currentDepletion: "Current depletion",
    rainExpectedRainReceived: "Rain expected. Rain received.",
    forecastAndSimulatedObservationsRemainSeparate: "Forecast and simulated observations remain separate",
    forecastRainfall: "Forecast rainfall",
    observedRainfall: "Observed rainfall",
    difference: "Difference",
    onlyObservedRainEntersTheActualWaterBalance: "Only observed rain enters the actual water balance.",
    currentCropNeed: "Current crop need",
    derivedConfiguredManagementPolicy: "Derived · configured management policy",
    targetDepletion: "Target depletion",
    currentNetRootZoneNeed: "Current net root-zone need",
    depthAndVolume: (value1: string | number, value2: string | number) => "" + value1 + " mm · " + value2 + "",
    applicationEfficiency: "Application efficiency",
    zoneEfficiency: (zone: string) => `Zone ${zone} application efficiency`,
    zoneSpecificGrossFormula: "Gross volume is the sum of each zone's net need divided by its configured efficiency. Field-equivalent depth is total volume divided by field area.",
    currentGrossWaterNeed: "Current gross water need",
    detailedCurrentVolume: "Detailed current volume",
    grossDepthNetDepthEfficiencyLitersDepthArea: "Gross depth = net depth ÷ efficiency; liters = depth × area.",
    planTargetsAndRemainingDelivery: "Plan targets and remaining delivery",
    simulatedFlowNominalFallbackWhenUnavailable: "Simulated flow · nominal fallback when unavailable",
    zonePlanTarget: (value1: string | number) => "Zone " + value1 + " · plan target",
    zoneRemaining: (value1: string | number) => "Zone " + value1 + " · remaining",
    totalPlanTarget: "Total plan target",
    alreadyDelivered: "Already delivered",
    remainingPlanDelivery: "Remaining plan delivery",
    remainingPumpTime: "Remaining pump time",
    targetsIncludeWaterAlreadyDeliveredAndMayBe: "Targets include water already delivered and may be revised after observed rain. Remaining time uses undelivered volume and flow, summed across sequential zones. Current crop need above may change during a run.",
    whyThisRecommendation: "Why this recommendation?",
    closeExplanation: "Close explanation",
    theScienceBehindYourPlan: "THE SCIENCE BEHIND YOUR PLAN",
    everyDropExplained: "Every drop, explained.",
    aTransparentPathFromWeatherAndSoilTo: "A transparent path from weather and soil to your irrigation recommendation.",
    engine: "Engine ",
  },
  fieldArt: {
    illustratedOneHectarePotatoFieldDividedIntoFour: "Illustrated one-hectare potato field divided into four irrigation zones",
  },
  fieldViews: {
    seasonLength: "/ 90 days",
    start: "Start",
    getToKnowYourGround: "GET TO KNOW YOUR GROUND",
    aLivingPictureOfYourField: "A living picture of your field.",
    fromTheRootsBelowToTheCropAbove: "From the roots below to the crop above. All in one place.",
    potato10Ha: "Potato · 1.0 ha",
    northPotatoField: "North Potato Field",
    text10Hectare: "1.0 hectare",
    totalGrowingArea: "Total growing area",
    text4Zones: "4 zones",
    sequentialDripIrrigation: "Sequential drip irrigation",
    loam: "Loam",
    homogeneousSoilProfile: "Homogeneous soil profile",
    configuredZoneSoilProfiles: "Configured zone soil profiles",
    zoneSoilStatus: "Water status by zone",
    zoneSoilSummary: "The field figures above are area-weighted summaries. Each configured zone has its own water balance and irrigation target.",
    zoneSoilVersion: (version: string) => `Zone soil model · ${version}`,
    zoneArea: "Area",
    zoneDepletion: "Depletion",
    zoneActionBoundary: "Action boundary",
    zoneTarget: "Target",
    zoneEfficiency: "Efficiency",
    areaWeightedDepletion: "Area-weighted root-zone depletion",
    areaWeightedSummary: "Area-weighted field summary",
    areaWeightedRootDepth: "Area-weighted root depth",
    areaWeightedRaw: "Area-weighted RAW",
    areaWeightedTarget: "Area-weighted target",
    zoneSpecificEfficiency: "Configured separately for each zone",
    theGrowingSeason: "The growing season",
    daysAfterPlanting: "Days after planting",
    configuredSimulationSeason: "Configured simulation season",
    plantingDate: "Planting date",
    currentBasalCoefficient: "Current basal coefficient",
    effectiveRootDepth: "Effective root depth",
    cropHeight: "Crop height",
    stageDurationsAreASimulationAssumptionDistinctFrom: "Stage durations are a simulation assumption, distinct from the 130-day FAO reference season.",
    howTheCropCoefficientChanges: "How the crop coefficient changes",
    aCloserLookBeneathTheSurface: "A closer look beneath the surface",
    text20CmShallow: "20 cm · shallow",
    text40CmRootZone: "40 cm · root zone",
    text60CmBelowRoots: "60 cm · below roots",
    fieldCapacity: "Field capacity",
    wiltingPoint: "Wilting point",
    sensorResponsesFollowModeledWettingAndDrainageWith: "Sensor responses follow modeled wetting and drainage with depth-dependent lag.",
    waterAvailableToYourCrop: "Water available to your crop",
    currentRootZoneDepletion: "Current root-zone depletion",
    totalAvailableWaterTaw: "Total available water (TAW)",
    actionThresholdRaw: "Action threshold (RAW)",
    postIrrigationTarget: "Post-irrigation target",
    canonicalWaterStateAppliesToTheWholeHomogeneous: "Canonical water state applies to the whole homogeneous field. Zones track delivered irrigation individually.",
    soilMoistureThroughTime: "Soil moisture through time",
    actionFailed: "Action failed.",
    rightWaterRightAmount: "RIGHT WATER. RIGHT AMOUNT.",
    yourIrrigationPlan: "Your irrigation plan.",
    fourZonesWorkingTogetherDeliveryYouCanFollow: "Four zones, working together. Delivery you can follow.",
    netRootZoneNeed: "Net root-zone need",
    grossDeliveryTarget: "Gross delivery target",
    totalEstimatedPumpTime: "Total estimated pump time",
    previewIrrigation: "Preview irrigation",
    pause: "Pause",
    resume: "Resume",
    stop: "Stop",
    sessionPreviewAdvancesAt60SpeedYourActions: "Session preview advances at 60× speed. Your actions do not change the shared farm.",
    deliveryCompleteTheFieldWaterBalanceReflectsThe: "Delivery complete. The field water balance reflects the water delivered.",
    oneZoneAtATime: "One zone at a time.",
    zone: "Zone ",
    deliveryProgress: "Delivery progress",
    currentFlow: "Current flow",
    pressure: "Pressure",
    estimatedRemaining: "Estimated remaining",
    valve: "Valve",
    deliveryNotJustATimer: "Delivery, not just a timer",
    eachZoneStopsWhenItsTargetVolumeHas: "Each zone stops when its target volume has passed. Runtime is an estimate based on flow; ramps and interruptions can change it.",
    deliveredSoFar: "Delivered so far",
    applicationEfficiency: "Application efficiency",
    pumpState: "Pump state",
    execution: "Execution",
    sequentialExecution: "Sequential · A → B → C → D",
    latestOperations: "Latest operations",
    operationsWillAppearHereWhenIrrigationBegins: "Operations will appear here when irrigation begins.",
    administratorSharedSimulatedControl: "Administrator · shared simulated control",
    theseControlsChangeTheAuthoritativeSharedDemonstration: "These controls change the authoritative shared demonstration.",
    aLittleForesight: "A LITTLE FORESIGHT",
    theWeekAhead: "The week ahead.",
    planAroundTheWeatherAdjustToWhatActually: "Plan around the weather. Adjust to what actually arrives.",
    text7DayPlanningOutlook: "7-day planning outlook",
    waterDemandExpectedRainfall: "Water demand & expected rainfall",
    rainExpectedVersusReceived: "Rain: expected versus received",
    forecast: "Forecast",
    observed: "Observed",
    difference: "Difference",
    forecastWindowEnds: "Forecast window ends",
    reconciliation: "Reconciliation",
    reconciliationComplete: "Complete",
    waitingForWindow: "Waiting for window",
    forecastRainSupportsPlanningItDoesNotChange: "Forecast rain supports planning. It does not change the actual field water balance until observed.",
    dayByDay: "Day by day",
    day: "Day",
    weather: "Weather",
    referenceEt: "Reference ET\u2080",
    cropEtc: "Crop ETc",
    expectedRain: "Expected rain",
    projectedDepletion: "Projected depletion",
    irrigationPlan: "Irrigation plan",
    today: "Today",
    watchForRain: "Watch for rain",
    monitor: "Monitor",
    projectionsIncludeHypotheticalFutureRainfallAndPlannedDelivery: "Projections include hypothetical future rainfall and planned delivery only in this planning view. They never overwrite observed state.",
    waitingForRainIsAllowedOnlyWhenThe: "Waiting for rain is allowed only when the field can stay below its action threshold throughout the expected rain window.",
    everyDropHasAStory: "EVERY DROP HAS A STORY",
    yourFieldSHistory: "Your field’s history.",
    aRecordOfTheWeatherWaterAndDecisions: "A record of the weather, water, and decisions that shaped your field.",
    rootZoneWaterBalance: "Root-zone water balance",
    depletion: "Depletion",
    referenceCropWaterUse: "Reference & crop water use",
    referenceEt2: "Reference ET₀",
    cropEt: "Crop ET",
    soilMoistureHistoryByDepth: "Soil moisture history by depth",
    simulatedObservationsAt2040And60Cm: "Simulated observations at 20, 40, and 60 cm. The 60 cm sensor is below the configured 50 cm root zone.",
    waterBalanceJournal: "Water balance journal",
    snapshotCountSuffix: " snapshots",
    recorded: "Recorded",
    etEtc: "ET₀ / ETc",
    rainObserved: "Rain observed",
    grossDelivered: "Gross delivered",
    noHistoryYetRecordedFieldEventsWillAppear: "No history yet. Recorded field events will appear here.",
    alertsObservations: "Alerts & observations",
    noAlertsRecorded: "No alerts recorded.",
    operationsTimeline: "Operations timeline",
    connectedToYourField: "CONNECTED TO YOUR FIELD",
    smallDevicesAFullerPicture: "Small devices. A fuller picture.",
    aSimpleViewOfTheInstrumentsBehindEvery: "A simple view of the instruments behind every decision.",
    devicesOnline: " devices online",
    deviceFilter: "Device filter",
    allDevices: "All devices",
    needsAttention: "Needs attention",
    irrigationSystem: "Irrigation system",
    zone2: (value1: string | number) => "Zone " + value1 + "",
    cmDepth: (value1: string | number) => " · " + value1 + " cm depth",
    updated: "Updated ",
    sourceProvenance: (value1: string | number, value2: string | number) => "Source: " + value1 + "; provenance: " + value2 + "",
    validReading: "Valid reading",
    allClear: "All clear.",
    noDevicesNeedAttention: "No devices need attention.",
    betterInputsClearerDecisions: "Better inputs, clearer decisions.",
    missingOrInconsistentReadingsAreFlaggedAndExcluded: " Missing or inconsistent readings are flagged and excluded from automatic control when necessary.",
  },
  growthTimeline: {
    stageNames: ["Initial", "Development", "Mid-season", "Late season"],
    dayCountSuffix: " days",
    potatoBasalCoefficientProgressionThe90DaySimulated: (value1: string | number, value2: string | number, value3: string | number, value4: string | number, value5: string | number) => "Potato basal coefficient progression. The 90-day simulated season starts at " + value1 + ", rises to " + value2 + " in mid-season, and ends at " + value3 + ". The dashed curve shows the 130-day reference example. Current day " + value4 + ", coefficient " + value5 + ".",
    basalCropCoefficientKcb: "Basal crop coefficient · Kcb",
    daysAfterPlanting: "Days after planting",
    todayDay: "Today · day ",
    kcb: " · Kcb ",
    text90DayDemoAssumption: "90-day demo assumption",
    text130DayReferenceExampleDashed: "130-day reference example · dashed",
    compareTheFourGrowthStages: "Compare the four growth stages",
    stage: "Stage",
    demoDays: "Demo days",
    referenceDays: "Reference days",
    kcbProgression: "Kcb progression",
    coefficientsAreReferenceInputsTheConfigured90Day: "Coefficients are reference inputs. The configured 90-day season is a simulation assumption; the 130-day FAO example is a comparison, not a fixed Tashkent growing calendar.",
  },
  irrigationHistory: {
    historyIsUnavailable: "History is unavailable.",
    recordedIrrigationSessions: "Recorded irrigation sessions",
    refreshIrrigationHistory: "Refresh irrigation history",
    loadingSavedSessions: "Loading saved sessions…",
    noSharedIrrigationSessionsHaveBeenRecordedSession: "No shared irrigation sessions have been recorded. Session previews stay local to your browser.",
    started: "Started",
    reason: "Reason",
    targetDelivered: "Target / delivered",
    elapsed: "Elapsed",
    zones: "Zones",
    status: "Status",
  },
  productProvider: {
    theFieldConnectionIsUnavailableReconnecting: "The field connection is unavailable. Reconnecting…",
    theActionCouldNotBeCompleted: "The action could not be completed.",
    simulationPaused: "Simulation paused.",
  },
  today: {
    aGoodDayToGrow: "A GOOD DAY TO GROW",
    yourFieldAtAGlance: "Your field, at a glance.",
    aClearPlanForHealthierCropsEveryDrop: "A clear plan for healthier crops. Every drop accounted for.",
    todaySRecommendation: "TODAY’S RECOMMENDATION",
    irrigationRecommendedToday: "Irrigation recommended today.",
    grossWaterDelivery: "Gross water delivery",
    mNetRootZoneNeed: (value1: string | number) => "" + value1 + " m³ net root-zone need",
    estimatedTimeZone: "Estimated time / zone",
    text4ZonesTotal: (value1: string | number) => "4 zones · " + value1 + " total",
    previewIrrigation: "Preview irrigation",
    potatoMidSeason1Hectare: "Potato · Mid-season · 1 hectare",
    rootZoneWater: "Root-zone water",
    areaWeightedRootZoneWater: "Root-zone water · field average",
    mmDepleted: "mm depleted",
    actionThreshold: "Action threshold: ",
    areaWeightedRaw: "Area-weighted RAW: ",
    todaySWeather: "Today’s weather",
    clearSkies: "Clear skies",
    wind: "° · Wind ",
    rainReceived: "Rain received",
    mmForecast: " mm forecast · ",
    windowComplete: "Window complete",
    awaitingRainfallWindow: "Awaiting rainfall window",
    systemHealth: "System health",
    readyToIrrigate: "Ready to irrigate",
    someInputsMissing: "Some inputs missing",
    needsAttention: "Needs attention",
    devicesOnline: " devices online",
    ofCount: " of ",
    dataQualitySuffix: " data",
    theWeekAhead: "The week ahead",
    text7DayOutlook: "7-day outlook",
    aLittleForesightGoesALongWay: "A little foresight goes a long way.",
    fieldNotes: "Field notes",
    latestUpdates: "Latest updates",
    yourFieldIsInGoodHands: "Your field is in good hands.",
    noActiveAlertsWeLlLetYouKnow: "No active alerts. We’ll let you know when something needs attention.",
    growingThrough: "Growing through ",
    day: "Day ",
    ofTheConfigured90DaySeasonConsistentRoot: " of the configured 90-day season. Consistent root-zone moisture matters.",
    viewFieldHistory: "View field history",
    beneathTheSurface: "Beneath the surface",
    exploreSoilProfile: "Explore soil profile",
    soilMoistureAtThreeDepthsVolumetricWaterContent: "Soil moisture at three depths · volumetric water content",
    yourCropGrowingSteadily: "Your crop, growing steadily",
    potato: "POTATO · ",
    daysSincePlanting: "days since planting",
    planted: "Planted ",
    rootDepth: " · Root depth ",
    getToKnowYourField: "Get to know your field",
    scienceYouCanFollow: "Science you can follow.",
    everyRecommendationConnectsWeatherCropGrowthAndThe: " Every recommendation connects weather, crop growth, and the water in your soil.",
  },
  ui: {
    viewDetails: "View details",
    fieldConnection: "FIELD CONNECTION",
    letSConnectYourField: "Let’s connect your field.",
    theFieldDatabaseIsCurrentlyUnavailable: "The field database is currently unavailable.",
    theApplicationWillShowYourSavedFieldState: "The application will show your saved field state as soon as the connection is restored.",
    retryConnection: "Retry connection",
  },
};
