'use client';
import { copy } from '@/config/copy';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { Activity, ArrowRight, Code, KeyRound, LockKeyhole, LogOut, Pause, Play, Plus, RefreshCw, RotateCcw, ShieldCheck } from 'lucide-react';
import { SCENARIOS } from '@/domain';
import { DEMO_FIELD_ID } from '@/lib/supabase/config';
import { useProduct } from './product-provider';
import { DeviceCredentials } from './device-credentials';
import { AdminAccess } from './admin-access';
import { DeviceIdentityForm, type RegisteredDevice } from './device-identity-form';
import { Badge, Card, EmptyBackend, Metric, PageHeading, StatRow } from './ui';
import { localDate, localTime, number, volume } from '@/lib/format';
export function AdminLogin({ forbidden = false }: { forbidden?: boolean }) {
  const router=useRouter();const {refreshSession}=useProduct();const [error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password')})});const result=await response.json();if(!response.ok)throw new Error(result.error??copy.admin.signInFailed);await refreshSession();router.refresh();}catch(e){setError(e instanceof Error?e.message:copy.admin.connectionUnavailable);}finally{setBusy(false);}}
  return <Card className="login-card"><span className="device-symbol" style={{marginBottom:24}}><LockKeyhole size={23}/></span><div className="eyebrow">{copy.admin.agriflowAdministration}</div><h1>{forbidden?copy.admin.administratorAccessRequired:copy.admin.welcomeBack}</h1><p>{forbidden?copy.admin.thisAccountDoesNotHaveAnAdministratorRole:copy.admin.signInToManageTheSharedFieldSimulation}</p><form onSubmit={login}><label className="form-field">{copy.admin.email}<input required type="email" name="email" autoComplete="username"/></label><label className="form-field">{copy.admin.password}<input required type="password" name="password" autoComplete="current-password" minLength={12}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?copy.admin.signingIn:copy.admin.signIn}<ArrowRight size={14}/></button></form><p className="fine-print">{copy.admin.accessIsProvisionedThroughAPrivilegedServerDatabase}</p></Card>;
}
type JsonRecord=Record<string,unknown>;
const ADMIN_TABS = [copy.admin.simulationLab,copy.admin.deviceIntegration,copy.admin.commissioning,copy.admin.calculationInspector,copy.admin.telemetry,copy.admin.agronomyParameters,copy.admin.alerts,copy.admin.auditLogs,copy.admin.teamAndAccess];
function JsonView({value}:{value:unknown}){return <pre className="json-view" tabIndex={0}>{JSON.stringify(value,null,2)}</pre>;}
export function AdminWorkspace({email,permissions,canManageAdmins}:{email:string;permissions:string[];canManageAdmins:boolean}){
  const visibleTabs=ADMIN_TABS.filter(tab=>tab===copy.admin.teamAndAccess?canManageAdmins:tab===copy.admin.simulationLab?permissions.includes('simulation.manage'):[copy.admin.deviceIntegration,copy.admin.commissioning,copy.admin.telemetry].includes(tab)?permissions.includes('devices.manage'):tab===copy.admin.agronomyParameters?permissions.includes('parameters.manage'):(tab===copy.admin.auditLogs||tab===copy.admin.calculationInspector)?permissions.includes('audit.read'):true);
  const router=useRouter();const{state,adminAction,refreshSession,simulationRunning,setSimulationRunning,speed,setSpeed,exitPreview,preview}=useProduct();
  const [tab,setTab]=useState<string>(visibleTabs[0]);const [overview,setOverview]=useState<JsonRecord>({});const[devices,setDevices]=useState<RegisteredDevice[]>([]);const[parameters,setParameters]=useState<JsonRecord[]>([]);const[calculations,setCalculations]=useState<JsonRecord[]>([]);const[selectedDevice,setSelectedDevice]=useState('');const[selectedCalculation,setSelectedCalculation]=useState(0);const[scenario,setScenario]=useState(state?.scenarioId??'rain-underperforms');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[credential,setCredential]=useState('');const[editingDevice,setEditingDevice]=useState<string|null>(null);const[parameterEditor,setParameterEditor]=useState(false);
  const load=useCallback(async()=>{try{const urls=['/api/admin/overview',permissions.includes('devices.manage')?'/api/admin/devices':null,permissions.includes('parameters.manage')?'/api/admin/parameters':null,permissions.includes('audit.read')?'/api/admin/calculations':null];const responses=await Promise.all(urls.map(url=>url?fetch(url,{cache:'no-store'}):Promise.resolve(null)));const data=await Promise.all(responses.map(r=>r?r.json():Promise.resolve({})));const failed=responses.findIndex(r=>r&&!r.ok);if(failed>=0)throw new Error(data[failed].error??copy.admin.unableToLoadAdministration);setOverview(data[0]);setDevices(data[1].devices??[]);setParameters(data[2].parameters??[]);setCalculations(data[3].calculations??[]);}catch(e){setMessage(e instanceof Error?e.message:copy.admin.unableToLoadAdministration);}},[permissions,setMessage]);
  useEffect(()=>{const task = window.setTimeout(() => void load(), 0); return () => clearTimeout(task);},[load]);
  async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await load();}catch(e){setMessage(e instanceof Error?e.message:copy.admin.actionFailed);}finally{setBusy(false);}}
  async function post(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??copy.admin.theActionFailed);return data;}
  async function saveDevice(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await action(async()=>{await post('/api/admin/devices',{id:form.get('id'),name:form.get('name'),kind:form.get('kind'),mode:form.get('mode'),fieldId:DEMO_FIELD_ID,...(form.get('zoneId')?{zoneId:form.get('zoneId')}:{}),enabled:devices.find(d=>d.id===editingDevice)?.enabled??true,configuration:JSON.parse(String(form.get('configuration')??'{}'))});setSelectedDevice(String(form.get('id')));setEditingDevice(null);setMessage(editingDevice?copy.admin.deviceConfigurationSaved:copy.admin.deviceRegistered);});}
  async function saveParameter(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await action(async()=>{await post('/api/admin/parameters',{kind:form.get('kind'),version:form.get('version'),name:form.get('name'),parameters:JSON.parse(String(form.get('parameters'))),source:{title:form.get('source'),organization:form.get('organization'),notes:form.get('notes')}});setParameterEditor(false);setMessage(copy.admin.newImmutableParameterVersionSaved);});}
  if(!state)return <EmptyBackend/>;
  const device=devices.find(d=>d.id===selectedDevice)??devices[0];const latest=Array.isArray(overview.latestDeviceState)?overview.latestDeviceState as JsonRecord[]:[];const normalized=latest.find(d=>d.device_id===device?.id)??state.devices.find(d=>d.id===device?.id);
  return <><PageHeading eyebrow={copy.admin.engineeringWorkspace} title={copy.admin.aClearerViewOfTheSystem} description={copy.admin.signedInAs(email)}><button className="button small" onClick={()=>void action(async()=>{setSimulationRunning(false);await post('/api/auth/logout',{});await refreshSession();router.refresh();})}><LogOut size={12}/>{copy.admin.signOut}</button></PageHeading>{preview&&<div className="insight-strip"><p>{copy.admin.exitYourLocalPreviewBeforeChangingTheShared}</p><button className="button" onClick={exitPreview}>{copy.admin.exitPreview}</button></div>}<div className="tabs" role="tablist" aria-label={copy.admin.adminSections}>{visibleTabs.map((t,index)=><button key={t} id={`admin-tab-${index}`} role="tab" aria-selected={tab===t} aria-controls="admin-panel" tabIndex={tab===t?0:-1} onKeyDown={event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%visibleTabs.length;else if(event.key==='ArrowLeft')next=(index+visibleTabs.length-1)%visibleTabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=visibleTabs.length-1;else return;event.preventDefault();setTab(visibleTabs[next]);setCredential('');document.getElementById(`admin-tab-${next}`)?.focus();void load();}} onClick={()=>{setTab(t);setCredential('');void load();}}>{t}</button>)}</div>{message&&<div role="status" className="insight-strip"><p>{message}</p></div>}
    <div role="tabpanel" id="admin-panel" aria-labelledby={`admin-tab-${visibleTabs.indexOf(tab)}`}>{tab==='Simulation Lab'&&<><Card title={copy.admin.deterministicScenarioControl} icon={Activity}><div className="admin-toolbar"><select className="select" aria-label={copy.admin.simulationScenario} value={scenario} onChange={e=>setScenario(e.target.value as typeof scenario)}>{SCENARIOS.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><button className="button" disabled={busy||preview} onClick={()=>void action(async()=>{setSimulationRunning(false);await adminAction('reset',{scenarioId:scenario});setMessage(copy.admin.scenarioResetToItsInitialCheckpoint);})}><RotateCcw size={13}/>{copy.admin.loadReset}</button><select className="select" aria-label={copy.admin.simulationSpeed} value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,10,60].map(v=><option key={v} value={v}>{v}{copy.admin.speed}</option>)}</select><button className="button primary" disabled={busy||preview} onClick={()=>void action(async()=>{await adminAction(simulationRunning?'pause':'run',{speed});setSimulationRunning(!simulationRunning);})}>{simulationRunning?<Pause size={13}/>:<Play size={13}/>} {simulationRunning?copy.admin.pause:copy.admin.run}</button><button className="button" disabled={busy||preview||simulationRunning} onClick={()=>void action(async()=>{await adminAction('advance',{seconds:60});})}>{copy.admin.step1Minute}</button></div><div className="grid four"><Metric label={copy.admin.simulationClock} value={localTime(state.clock)} hint={localDate(state.clock,{year:'numeric'})}/><Metric label={copy.admin.currentDepletion} value={number(state.soil.rootZoneDepletionMm,2)} unit="mm"/><Metric label={copy.admin.deliveredIrrigation} value={number(state.control.deliveredVolumeLiters/1000,2)} unit="m³"/><Metric label={copy.admin.dataCompleteness} value={state.recommendation.confidence}/></div><p className="fine-print">{copy.admin.runControlsTheScenarioClockStartIrrigationFrom}</p></Card><div className="grid two section-gap"><Card title={copy.admin.currentRecommendation}><h3>{state.recommendation.title}</h3><p className="card-description" style={{marginTop:0}}>{state.recommendation.reason}</p><StatRow label={copy.admin.grossDelivery} value={volume(state.recommendation.grossVolumeLiters)}/><StatRow label={copy.admin.stateVersion} value={state.version}/><StatRow label={copy.admin.engine} value={state.calculation.engineVersion}/></Card><Card title={copy.admin.scenarioEvents}>{state.events.slice(-8).reverse().map(e=><div className="timeline-item" key={e.id}><time>{localTime(e.at)}</time><p>{e.message}</p></div>)}</Card></div></>}
    {tab==='Device Integration'&&<><Card title={copy.admin.registeredDeviceIdentities} action={<button className="button small" onClick={()=>setEditingDevice(editingDevice===null?'':null)}><Plus size={12}/>{copy.admin.registerDevice}</button>}>{editingDevice!==null&&<DeviceIdentityForm key={editingDevice} device={devices.find(d=>d.id===editingDevice)} busy={busy} onSubmit={saveDevice} onCancel={()=>setEditingDevice(null)}/>}<div className="table-wrap" tabIndex={0}><table><thead><tr>{[copy.admin.device,copy.admin.identity,copy.admin.mode,copy.admin.binding,copy.admin.inspect].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{devices.map(d=><tr key={d.id}><td><strong>{d.name}</strong></td><td>{d.id}</td><td><Badge tone="neutral">{d.mode}</Badge></td><td>{d.zone_id?copy.admin.zone(d.zone_id):copy.admin.field}</td><td><button className="button small" onClick={()=>{setSelectedDevice(d.id);setCredential('');}}>{copy.admin.inspect}</button></td></tr>)}</tbody></table></div></Card>{device&&<Card className="section-gap" title={copy.admin.integrationDetail(device.name)}><div className="grid two"><div><h3>{copy.admin.registeredConfiguration}</h3><JsonView value={device}/></div><div><h3>{copy.admin.latestNormalizedReading}</h3><JsonView value={normalized??copy.admin.noNormalizedReading}/></div></div><div className="control-actions"><button className="button" disabled={busy} onClick={()=>{setEditingDevice(device.id);window.scrollTo({top:0,behavior:'instant'});}}>{copy.admin.editConfiguration}</button><button className="button" disabled={busy} onClick={()=>void action(async()=>{const result=await post(`/api/admin/devices/${device.id}/credentials`,{});setCredential(result.token??result.credential??'');})}><KeyRound size={13}/>{copy.admin.issueDeviceCredential}</button><button className="button" disabled={busy} onClick={()=>void action(async()=>{await post('/api/admin/devices',{id:device.id,name:device.name,kind:device.kind,mode:device.mode,fieldId:device.field_id,...(device.zone_id?{zoneId:device.zone_id}:{}),enabled:!device.enabled,configuration:device.configuration});setMessage(device.enabled?copy.admin.deviceDisabled:copy.admin.deviceEnabled);})}>{device.enabled?copy.admin.disable:copy.admin.enable}{copy.admin.deviceActionSuffix}</button></div>{credential&&<div className="formula"><strong>{copy.admin.copyThisCredentialNowItIsShownOnly}</strong><code style={{display:'block',overflowWrap:'anywhere',marginTop:9}}>{credential}</code><button className="button small" onClick={()=>{void navigator.clipboard.writeText(credential);setMessage(copy.admin.credentialCopied);}}>{copy.admin.copy}</button></div>}<DeviceCredentials deviceId={device.id} refreshKey={credential}/></Card>}</>}
    {tab==='Commissioning'&&<Card title={copy.admin.commissioningPreparation} icon={ShieldCheck}><p className="card-description">{copy.admin.allCurrentChecksAreSimulatedPhysicalCalibrationRemains}</p><div className="admin-toolbar"><select className="select" aria-label={copy.admin.commissioningDevice} value={device?.id??''} onChange={e=>setSelectedDevice(e.target.value)}>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="button primary" disabled={!device||busy} onClick={()=>void action(async()=>{await post('/api/admin/commissioning',{deviceId:device.id});setMessage(copy.admin.simulatedCommissioningChecksRecordedNoPhysicalTestWas);})}>{copy.admin.runSimulatedChecks}</button></div><JsonView value={overview.commissioning??[]}/></Card>}
    {tab==='Calculation Inspector'&&<Card title={copy.admin.reproducibleCalculationSnapshots} icon={Code}><div className="admin-toolbar"><select className="select" aria-label={copy.admin.calculationSnapshot} value={selectedCalculation} onChange={e=>setSelectedCalculation(Number(e.target.value))}>{calculations.map((c,i)=><option value={i} key={String(c.id??i)}>{String(c.calculated_at??c.created_at??c.id)} · {String(c.engine_version??'engine')}</option>)}</select></div><JsonView value={calculations[selectedCalculation]??state.calculation}/><p className="fine-print">{copy.admin.snapshotsPreserveRawInputsNormalizedValuesIntermediateCalculations}</p></Card>}
    {tab==='Telemetry'&&<Card title={copy.admin.receivedTelemetry} action={<button className="button small" onClick={()=>void load()}><RefreshCw size={12}/>{copy.admin.refresh}</button>}><JsonView value={overview.telemetry??[]}/></Card>}
    {tab==='Agronomy Parameters'&&<Card title={copy.admin.versionedParameterSets} action={<button className="button small" onClick={()=>setParameterEditor(!parameterEditor)}><Plus size={12}/>{copy.admin.newVersion}</button>}>{parameterEditor&&<form onSubmit={saveParameter}><div className="grid two"><label className="form-field">{copy.admin.kind}<select name="kind">{['crop','soil','policy','irrigation','simulation'].map(k=><option key={k}>{k}</option>)}</select></label><label className="form-field">{copy.admin.version}<input name="version" required placeholder="1.0.1"/></label><label className="form-field">{copy.admin.name}<input name="name" required/></label><label className="form-field">{copy.admin.sourceTitle}<input name="source" required/></label><label className="form-field">{copy.admin.sourceOrganization}<input name="organization" required/></label><label className="form-field">{copy.admin.assumptionsNotes}<input name="notes" required/></label></div><label className="form-field">{copy.admin.parametersJson}<textarea name="parameters" required rows={8} className="json-view" defaultValue={'{\n  "notes": "Document each reference or simulation assumption"\n}'}/></label><button className="button primary" disabled={busy}>{copy.admin.saveNewImmutableVersion}</button><p className="fine-print">{copy.admin.savingAReferenceVersionDoesNotSilentlyAlter}</p></form>}<JsonView value={parameters}/></Card>}
    {tab==='Alerts'&&<Card title={copy.admin.evidenceAndPossibleCauses}><JsonView value={overview.alerts??state.alerts}/></Card>}
    {tab===copy.admin.teamAndAccess&&<AdminAccess/>}
    {tab==='Audit Logs'&&<Card title={copy.admin.authoritativeMutationAudit}><JsonView value={overview.auditLogs??[]}/></Card>}</div>
  </>;
}
