'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { Activity, ArrowRight, Code, KeyRound, LockKeyhole, LogOut, Pause, Play, Plus, RefreshCw, RotateCcw, ShieldCheck } from 'lucide-react';
import { SCENARIOS } from '@/domain';
import { DEMO_FIELD_ID } from '@/lib/supabase/config';
import { useProduct } from './product-provider';
import { DeviceCredentials } from './device-credentials';
import { Badge, Card, EmptyBackend, Metric, PageHeading, StatRow } from './ui';
import { localDate, localTime, number, volume } from '@/lib/format';
export function AdminLogin({ forbidden = false }: { forbidden?: boolean }) {
  const router=useRouter();const {refreshSession}=useProduct();const [error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password')})});const result=await response.json();if(!response.ok)throw new Error(result.error??'Sign-in failed.');await refreshSession();router.refresh();}catch(e){setError(e instanceof Error?e.message:'Connection unavailable.');}finally{setBusy(false);}}
  return <Card className="login-card"><span className="device-symbol" style={{marginBottom:24}}><LockKeyhole size={23}/></span><div className="eyebrow">AGRIFLOW ADMINISTRATION</div><h1>{forbidden?'Administrator access required.':'Welcome back.'}</h1><p>{forbidden?'This account does not have an administrator role. Sign in with an authorized account.':'Sign in to manage the shared field simulation and integration tools.'}</p><form onSubmit={login}><label className="form-field">Email<input required type="email" name="email" autoComplete="username"/></label><label className="form-field">Password<input required type="password" name="password" autoComplete="current-password" minLength={12}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight size={14}/></button></form><p className="fine-print">Access is provisioned through a privileged server/database bootstrap. Accounts cannot assign themselves an administrator role.</p></Card>;
}
type JsonRecord=Record<string,unknown>;
type RegisteredDevice={id:string;name:string;kind:string;mode:string;field_id:string;zone_id:string|null;enabled:boolean;configuration:JsonRecord};
function JsonView({value}:{value:unknown}){return <pre className="json-view">{JSON.stringify(value,null,2)}</pre>;}
export function AdminWorkspace({email}:{email:string}){
  const router=useRouter();const{state,adminAction,refreshSession,simulationRunning,setSimulationRunning,speed,setSpeed,exitPreview,preview}=useProduct();
  const [tab,setTab]=useState('Simulation Lab');const [overview,setOverview]=useState<JsonRecord>({});const[devices,setDevices]=useState<RegisteredDevice[]>([]);const[parameters,setParameters]=useState<JsonRecord[]>([]);const[calculations,setCalculations]=useState<JsonRecord[]>([]);const[selectedDevice,setSelectedDevice]=useState('');const[selectedCalculation,setSelectedCalculation]=useState(0);const[scenario,setScenario]=useState(state?.scenarioId??'rain-underperforms');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[credential,setCredential]=useState('');const[register,setRegister]=useState(false);const[parameterEditor,setParameterEditor]=useState(false);
  const load=useCallback(async()=>{try{const responses=await Promise.all(['/api/admin/overview','/api/admin/devices','/api/admin/parameters','/api/admin/calculations'].map(url=>fetch(url,{cache:'no-store'})));const data=await Promise.all(responses.map(r=>r.json()));const failed=responses.findIndex(r=>!r.ok);if(failed>=0)throw new Error(data[failed].error??'Unable to load administration.');setOverview(data[0]);setDevices(data[1].devices??[]);setParameters(data[2].parameters??[]);setCalculations(data[3].calculations??[]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load administration.');}},[]);
  useEffect(()=>{const task = window.setTimeout(() => void load(), 0); return () => clearTimeout(task);},[load]);
  async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await load();}catch(e){setMessage(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}
  async function post(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??'The action failed.');return data;}
  async function saveDevice(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await action(async()=>{await post('/api/admin/devices',{id:form.get('id'),name:form.get('name'),kind:form.get('kind'),mode:form.get('mode'),fieldId:DEMO_FIELD_ID,enabled:true,configuration:{}});setRegister(false);setMessage('Device registered.');});}
  async function saveParameter(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await action(async()=>{await post('/api/admin/parameters',{kind:form.get('kind'),version:form.get('version'),name:form.get('name'),parameters:JSON.parse(String(form.get('parameters'))),source:{title:form.get('source'),organization:form.get('organization'),notes:form.get('notes')}});setParameterEditor(false);setMessage('New immutable parameter version saved.');});}
  if(!state)return <EmptyBackend/>;
  const device=devices.find(d=>d.id===selectedDevice)??devices[0];const latest=Array.isArray(overview.latestDeviceState)?overview.latestDeviceState as JsonRecord[]:[];const normalized=latest.find(d=>d.device_id===device?.id)??state.devices.find(d=>d.id===device?.id);
  return <><PageHeading eyebrow="ENGINEERING WORKSPACE" title="A clearer view of the system." description={`Signed in as ${email}`}><button className="button small" onClick={()=>void action(async()=>{setSimulationRunning(false);await post('/api/auth/logout',{});await refreshSession();router.refresh();})}><LogOut size={12}/>Sign out</button></PageHeading>{preview&&<div className="insight-strip"><p>Exit your local preview before changing the shared simulation.</p><button className="button" onClick={exitPreview}>Exit preview</button></div>}<div className="tabs" role="tablist" aria-label="Admin sections">{['Simulation Lab','Device Integration','Commissioning','Calculation Inspector','Telemetry','Agronomy Parameters','Alerts','Audit Logs'].map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>{setTab(t);setCredential('');void load();}}>{t}</button>)}</div>{message&&<div role="status" className="insight-strip"><p>{message}</p></div>}
    {tab==='Simulation Lab'&&<><Card title="Deterministic scenario control" icon={Activity}><div className="admin-toolbar"><select className="select" aria-label="Simulation scenario" value={scenario} onChange={e=>setScenario(e.target.value as typeof scenario)}>{SCENARIOS.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><button className="button" disabled={busy||preview} onClick={()=>void action(async()=>{setSimulationRunning(false);await adminAction('reset',{scenarioId:scenario});setMessage('Scenario reset to its initial checkpoint.');})}><RotateCcw size={13}/>Load / reset</button><select className="select" aria-label="Simulation speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,10,60].map(v=><option key={v} value={v}>{v}× speed</option>)}</select><button className="button primary" disabled={busy||preview} onClick={()=>void action(async()=>{await adminAction(simulationRunning?'pause':'run',{speed});setSimulationRunning(!simulationRunning);})}>{simulationRunning?<Pause size={13}/>:<Play size={13}/>} {simulationRunning?'Pause':'Run'}</button><button className="button" disabled={busy||preview||simulationRunning} onClick={()=>void action(async()=>{await adminAction('advance',{seconds:60});})}>Step 1 minute</button></div><div className="grid four"><Metric label="Simulation clock" value={localTime(state.clock)} hint={localDate(state.clock,{year:'numeric'})}/><Metric label="Current depletion" value={number(state.soil.rootZoneDepletionMm,2)} unit="mm"/><Metric label="Delivered irrigation" value={number(state.control.deliveredVolumeLiters/1000,2)} unit="m³"/><Metric label="Data completeness" value={state.recommendation.confidence}/></div><p className="fine-print">Run controls the scenario clock. Start irrigation from the Irrigation page’s administrator controls. Advancement continues across navigation while this session remains open.</p></Card><div className="grid two section-gap"><Card title="Current recommendation"><h3>{state.recommendation.title}</h3><p className="card-description" style={{marginTop:0}}>{state.recommendation.reason}</p><StatRow label="Gross delivery" value={volume(state.recommendation.grossVolumeLiters)}/><StatRow label="State version" value={state.version}/><StatRow label="Engine" value={state.calculation.engineVersion}/></Card><Card title="Scenario events">{state.events.slice(-8).reverse().map(e=><div className="timeline-item" key={e.id}><time>{localTime(e.at)}</time><p>{e.message}</p></div>)}</Card></div></>}
    {tab==='Device Integration'&&<><Card title="Registered device identities" action={<button className="button small" onClick={()=>setRegister(!register)}><Plus size={12}/>Register device</button>}>{register&&<form onSubmit={saveDevice}><div className="grid two"><label className="form-field">Device ID<input name="id" required pattern="[A-Za-z0-9_-]+"/></label><label className="form-field">Name<input name="name" required/></label><label className="form-field">Kind<select name="kind">{['weather','rain','soil','flow','pressure','valve','pump'].map(k=><option key={k}>{k}</option>)}</select></label><label className="form-field">Source mode<select name="mode"><option>SIMULATED</option><option>MEASURED</option></select></label></div><button className="button primary" disabled={busy}>Save identity</button></form>}<div className="table-wrap"><table><thead><tr>{['Device','Identity','Mode','Binding','Inspect'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{devices.map(d=><tr key={d.id}><td><strong>{d.name}</strong></td><td>{d.id}</td><td><Badge tone="neutral">{d.mode}</Badge></td><td>{d.zone_id?`Zone ${d.zone_id}`:'Field'}</td><td><button className="button small" onClick={()=>{setSelectedDevice(d.id);setCredential('');}}>Inspect</button></td></tr>)}</tbody></table></div></Card>{device&&<Card className="section-gap" title={`${device.name} · integration detail`}><div className="grid two"><div><h3>Registered configuration</h3><JsonView value={device}/></div><div><h3>Latest normalized reading</h3><JsonView value={normalized??'No simulated reading for this identity. Inspect incoming telemetry below.'}/></div></div><div className="control-actions"><button className="button" disabled={busy} onClick={()=>void action(async()=>{const result=await post(`/api/admin/devices/${device.id}/credentials`,{});setCredential(result.token??result.credential??'');})}><KeyRound size={13}/>Issue device credential</button><button className="button" disabled={busy} onClick={()=>void action(async()=>{await post('/api/admin/devices',{id:device.id,name:device.name,kind:device.kind,mode:device.mode,fieldId:device.field_id,...(device.zone_id?{zoneId:device.zone_id}:{}),enabled:!device.enabled,configuration:device.configuration});setMessage(device.enabled?'Device disabled.':'Device enabled.');})}>{device.enabled?'Disable':'Enable'} device</button></div>{credential&&<div className="formula"><strong>Copy this credential now. It is shown only once.</strong><code style={{display:'block',overflowWrap:'anywhere',marginTop:9}}>{credential}</code><button className="button small" onClick={()=>{void navigator.clipboard.writeText(credential);setMessage('Credential copied.');}}>Copy</button></div>}<DeviceCredentials deviceId={device.id} refreshKey={credential}/></Card>}</>}
    {tab==='Commissioning'&&<Card title="Commissioning preparation" icon={ShieldCheck}><p className="card-description">All current checks are simulated. Physical calibration remains pending until hardware is connected.</p><div className="admin-toolbar"><select className="select" aria-label="Commissioning device" value={device?.id??''} onChange={e=>setSelectedDevice(e.target.value)}>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="button primary" disabled={!device||busy} onClick={()=>void action(async()=>{await post('/api/admin/commissioning',{deviceId:device.id});setMessage('Simulated commissioning checks recorded. No physical test was performed.');})}>Run simulated checks</button></div><JsonView value={overview.commissioning??[]}/></Card>}
    {tab==='Calculation Inspector'&&<Card title="Reproducible calculation snapshots" icon={Code}><div className="admin-toolbar"><select className="select" aria-label="Calculation snapshot" value={selectedCalculation} onChange={e=>setSelectedCalculation(Number(e.target.value))}>{calculations.map((c,i)=><option value={i} key={String(c.id??i)}>{String(c.calculated_at??c.created_at??c.id)} · {String(c.engine_version??'engine')}</option>)}</select></div><JsonView value={calculations[selectedCalculation]??state.calculation}/><p className="fine-print">Snapshots preserve raw inputs, normalized values, intermediate calculations, versions, and provenance.</p></Card>}
    {tab==='Telemetry'&&<Card title="Received telemetry" action={<button className="button small" onClick={()=>void load()}><RefreshCw size={12}/>Refresh</button>}><JsonView value={overview.telemetry??[]}/></Card>}
    {tab==='Agronomy Parameters'&&<Card title="Versioned parameter sets" action={<button className="button small" onClick={()=>setParameterEditor(!parameterEditor)}><Plus size={12}/>New version</button>}>{parameterEditor&&<form onSubmit={saveParameter}><div className="grid two"><label className="form-field">Kind<select name="kind">{['crop','soil','policy','irrigation','simulation'].map(k=><option key={k}>{k}</option>)}</select></label><label className="form-field">Version<input name="version" required placeholder="1.0.1"/></label><label className="form-field">Name<input name="name" required/></label><label className="form-field">Source title<input name="source" required/></label><label className="form-field">Source organization<input name="organization" required/></label><label className="form-field">Assumptions / notes<input name="notes" required/></label></div><label className="form-field">Parameters (JSON)<textarea name="parameters" required rows={8} className="json-view" defaultValue={'{\n  "notes": "Document each reference or simulation assumption"\n}'}/></label><button className="button primary" disabled={busy}>Save new immutable version</button><p className="fine-print">Saving a reference version does not silently alter active or historical calculations.</p></form>}<JsonView value={parameters}/></Card>}
    {tab==='Alerts'&&<Card title="Evidence and possible causes"><JsonView value={overview.alerts??state.alerts}/></Card>}
    {tab==='Audit Logs'&&<Card title="Authoritative mutation audit"><JsonView value={overview.auditLogs??[]}/></Card>}
  </>;
}
