'use client';
import { useCopy } from '@/config/locale-copy';
import { Area, AreaChart, Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useReducedMotion } from 'motion/react';
import { buildForecast, type SimulationState } from '@/domain';
import { useFormat } from '@/lib/use-format';
const tooltip = { background: '#fffefa', border: '1px solid #e0e7d7', borderRadius: 8, fontSize: 10 };
export function OutlookChart({ state }: { state: SimulationState }) {const { localDate, number } = useFormat();const copy = useCopy();
  const reducedMotion = useReducedMotion();
  const data = buildForecast(state).map(day => ({ ...day, day: localDate(`${day.date}T12:00:00Z`, { weekday: 'short', month: undefined, day: undefined }), irrigationMm: day.grossVolumeLiters / state.field.areaM2 }));
  return <><div className="chart" role="img" aria-label={copy.charts.sevenDayForecastTodaySEstimatedCropWater(number(data[0].etcMm))}><ResponsiveContainer width="100%" height="100%" minWidth={0}><ComposedChart data={data} margin={{ top: 15, right: 3, left: -28, bottom: 0 }} barGap={4}><CartesianGrid vertical={false} stroke="#edf0e4" strokeDasharray="3 4" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#929c85', fontSize: 9 }} dy={7} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#a0aa94', fontSize: 9 }} /><Tooltip contentStyle={tooltip} formatter={(value, name) => [`${number(Number(value))} mm`, name]} /><Bar isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.plannedGrossIrrigation} dataKey="irrigationMm" fill="#8aa571" radius={[3,3,0,0]} maxBarSize={16} /><Bar isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.forecastRain} dataKey="rainfallMm" fill="#adc8cf" radius={[3,3,0,0]} maxBarSize={16} /><Line isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.cropWaterUse} dataKey="etcMm" stroke="#d6b370" strokeWidth={1.5} dot={{ r: 2.5, fill: '#d6b370', strokeWidth: 0 }} /></ComposedChart></ResponsiveContainer></div><div className="chart-caption"><span className="chart-key"><i />{copy.charts.plannedIrrigation}</span><span className="chart-key"><i className="blue" />{copy.charts.forecastRain}</span><span className="chart-key"><i className="amber" />{copy.charts.cropWaterUse}</span><span>{copy.charts.mmPerDay}</span></div></>;
}
export function MoistureChart({ state }: { state: SimulationState }) {const { localDate, number } = useFormat();const copy = useCopy();
  const reducedMotion = useReducedMotion();
  const data = state.history.map(point => ({ ...point, day: localDate(point.at) }));
  return <><div className="chart" role="img" aria-label={copy.charts.soilMoistureAt2040And60Centimeters(number(state.soil.moisture20Pct))}><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{ top: 12, right: 3, left: -22, bottom: 0 }}><defs><linearGradient id="moisture-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#abc184" stopOpacity={.22} /><stop offset="1" stopColor="#abc184" stopOpacity={.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0e4" strokeDasharray="3 4" /><XAxis dataKey="day" axisLine={false} tickLine={false} minTickGap={25} tick={{ fill: '#929c85', fontSize: 9 }} dy={6} /><YAxis domain={['auto','auto']} axisLine={false} tickLine={false} tick={{ fill: '#a0aa94', fontSize: 9 }} tickFormatter={v => `${Math.round(v)}%`} /><Tooltip contentStyle={tooltip} formatter={(value, name) => [`${number(Number(value))}%`, name]} /><Area isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.text20Cm} dataKey="soilMoisture20Pct" stroke="#729555" fill="url(#moisture-area)" strokeWidth={2} /><Line isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.text40Cm} dataKey="soilMoisture40Pct" stroke="#a0b887" strokeWidth={1.5} dot={false} /><Line isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.text60Cm} dataKey="soilMoisture60Pct" stroke="#a7c4ca" strokeWidth={1.5} strokeDasharray="4 3" dot={false} /></AreaChart></ResponsiveContainer></div><div className="chart-caption"><span className="chart-key"><i />{copy.charts.text20Cm}</span><span className="chart-key"><i className="pale" />{copy.charts.text40Cm}</span><span className="chart-key"><i className="blue" />{copy.charts.text60CmBelowRootZone}</span></div></>;
}
export function BalanceChart({ state }: { state: SimulationState }) {const { localDate } = useFormat();const copy = useCopy(); const reducedMotion = useReducedMotion(); return <div className="chart" role="img" aria-label={copy.charts.rootZoneDepletionHistoryComparedWithTheReadily}><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={state.history.map(h => ({ ...h, day: localDate(h.at) }))} margin={{ top: 15, right: 25, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edf0e4" /><XAxis dataKey="day" axisLine={false} tickLine={false} minTickGap={25} /><YAxis axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Area isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.depletionMm} dataKey="depletionMm" stroke="#8ba767" fill="#e9efdc" strokeWidth={2} /><Line isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.rawMm} dataKey="rawMm" stroke="#a28344" strokeDasharray="4 4" dot={false} /></AreaChart></ResponsiveContainer></div>; }
export function EtChart({ state }: { state: SimulationState }) {const { localDate } = useFormat();const copy = useCopy(); const reducedMotion = useReducedMotion(); return <div className="chart" role="img" aria-label={copy.charts.referenceEvapotranspirationAndCropEvapotranspirationHistory}><ResponsiveContainer width="100%" height="100%" minWidth={0}><ComposedChart data={state.history.map(h => ({ ...h, day: localDate(h.at) }))} margin={{ top: 15, right: 10, left: -25, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edf0e4" /><XAxis dataKey="day" axisLine={false} tickLine={false} minTickGap={25} /><YAxis axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Bar isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.referenceEtMm} dataKey="etoMm" fill="#cbd8b5" radius={[3,3,0,0]} maxBarSize={20} /><Line isAnimationActive={!reducedMotion} animationDuration={450} name={copy.charts.cropEtMm} dataKey="etcMm" stroke="#6b9557" dot={false} strokeWidth={2} /></ComposedChart></ResponsiveContainer></div>; }
