'use client';
import { copy } from '@/config/copy';
import { useCallback, useEffect, useState } from 'react';
import { Badge } from './ui';
import { localDate } from '@/lib/format';
type Credential = { id:string; prefix:string; createdAt:string; expiresAt:string|null; revokedAt:string|null; lastUsedAt:string|null };
export function DeviceCredentials({deviceId,refreshKey}:{deviceId:string;refreshKey:string}) {
  const [credentials,setCredentials]=useState<Credential[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[checkedAt,setCheckedAt]=useState(0);
  const load=useCallback(async()=>{try{const r=await fetch(`/api/admin/devices/${encodeURIComponent(deviceId)}/credentials`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setCredentials(d.credentials??[]);setCheckedAt(Date.now());setError('');}catch(e){setError(e instanceof Error?e.message:copy.deviceCredentials.credentialMetadataUnavailable);}},[deviceId]);
  useEffect(()=>{const task=setTimeout(()=>void load(),0);return()=>clearTimeout(task);},[load,refreshKey]);
  async function revoke(id:string){setBusy(true);try{const r=await fetch(`/api/admin/devices/${encodeURIComponent(deviceId)}/credentials`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:copy.deviceCredentials.revocationFailed);}finally{setBusy(false);}}
  return <div style={{marginTop:24}}><h3>{copy.deviceCredentials.credentialLifecycle}</h3>{error&&<p role="alert" className="form-error">{error}</p>}{credentials.length?<div className="table-wrap" tabIndex={0}><table><thead><tr>{[copy.deviceCredentials.prefix,copy.deviceCredentials.created,copy.deviceCredentials.lastUsed,copy.deviceCredentials.status,copy.deviceCredentials.action].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{credentials.map(c=><tr key={c.id}><td><code>{c.prefix}…</code></td><td>{localDate(c.createdAt)}</td><td>{c.lastUsedAt?localDate(c.lastUsedAt):copy.deviceCredentials.never}</td><td><Badge tone={c.revokedAt?'neutral':'green'}>{c.revokedAt?copy.deviceCredentials.revoked:c.expiresAt&&Date.parse(c.expiresAt)<checkedAt?copy.deviceCredentials.expired:copy.deviceCredentials.active}</Badge></td><td><button className="button small danger" disabled={busy||!!c.revokedAt} onClick={()=>void revoke(c.id)}>{copy.deviceCredentials.revoke}</button></td></tr>)}</tbody></table></div>:<p className="stat-caption">{copy.deviceCredentials.noCredentialsIssuedForThisDevice}</p>}</div>;
}
