'use client';
import { useCopy } from '@/config/locale-copy';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowUpRight, Info, X } from 'lucide-react';
import { useProduct } from './product-provider';
import { StatRow } from './ui';
import { useFormat } from '@/lib/use-format';
import { brand } from '@/config/brand';
import { zoneRemainingMinutes } from '@/domain';
export function Explanation({ className = 'button ghost' }: { className?: string }) {const { duration, number, volume } = useFormat();const copy = useCopy();
  const { state } = useProduct(); if (!state) return null;
  const c = state.calculation, r = state.recommendation;
  const planTargetLiters = state.zones.reduce((total, zone) => total + zone.targetVolumeLiters, 0);
  const planDeliveredLiters = state.zones.reduce((total, zone) => total + zone.deliveredVolumeLiters, 0);
  const planRemainingLiters = state.zones.reduce((total, zone) => total + Math.max(0, zone.targetVolumeLiters - zone.deliveredVolumeLiters), 0);
  const remainingPumpMinutes = state.zones.reduce((total, zone) => total + zoneRemainingMinutes(zone), 0);
  const efficiencyRows: [string,string][] = state.soilModel
    ? state.soilModel.zones.map(zone=>[copy.explanation.zoneEfficiency(zone.zoneId),`${number(zone.parameters.applicationEfficiency*100,0)}%`])
    : [[copy.explanation.applicationEfficiency,`${number(state.parameters.applicationEfficiency*100,0)}%`]];
  const steps = [
    { title: copy.explanation.weatherSetsTheStartingPoint, source: copy.explanation.simulatedWeatherFao56Equations640, rows: [[copy.explanation.temperatureRange, `${state.weather.temperatureMinC}–${state.weather.temperatureMaxC} °C`],[copy.explanation.relativeHumidity,`${state.weather.relativeHumidityMinPct}–${state.weather.relativeHumidityMaxPct}%`],[copy.explanation.windAt2M,`${number(state.weather.windSpeedMps)} m/s`],[copy.explanation.solarRadiation,`${number(state.weather.solarRadiationMjM2Day)} MJ/m²/day`],[copy.explanation.referenceEt,`${number(c.etoMm,2)} mm/day`]] },
    { title: copy.explanation.potatoInItsGrowingSeason, source: copy.explanation.referenceParameters(c.parameterVersion), rows: [[copy.explanation.growthStage,state.field.growthStage],[copy.explanation.basalCoefficientKcb,number(c.kcb,2)],[copy.explanation.evaporationCoefficientKe,number(c.ke,4)],[copy.explanation.waterStressCoefficientKs,number(c.ks,3)],[copy.explanation.cropWaterUse,`${number(c.etcMm,2)} mm/day`]], formula: copy.explanation.etcKsKcbKeEt },
    { title: copy.explanation.waterStoredInTheRootZone, source: state.soilModel?copy.explanation.derivedZoneSoilSummary:copy.explanation.derivedFieldLevelWaterBalance, rows: [[copy.explanation.rootDepth,`${number(state.field.rootDepthM,2)} m`],[copy.explanation.totalAvailableWater,`${number(c.tawMm)} mm`],[copy.explanation.readilyAvailableWater,`${number(state.soil.rawMm,2)} mm`],[copy.explanation.currentDepletion,`${number(state.soil.rootZoneDepletionMm,2)} mm`]] },
    { title: copy.explanation.rainExpectedRainReceived, source: copy.explanation.forecastAndSimulatedObservationsRemainSeparate, rows: [[copy.explanation.forecastRainfall,`${number(state.rain.forecastMm)} mm`],[copy.explanation.observedRainfall,`${number(state.rain.observedMm)} mm`],[copy.explanation.difference,`${number(state.rain.observedMm-state.rain.forecastMm)} mm`]], formula: copy.explanation.onlyObservedRainEntersTheActualWaterBalance },
    { title: copy.explanation.currentCropNeed, source: copy.explanation.derivedConfiguredManagementPolicy, rows: [[copy.explanation.targetDepletion,`${number(r.targetDepletionMm,2)} mm`],[copy.explanation.currentNetRootZoneNeed,copy.explanation.depthAndVolume(number(r.netDepthMm,2), volume(r.netVolumeLiters))],...efficiencyRows,[copy.explanation.currentGrossWaterNeed,copy.explanation.depthAndVolume(number(r.grossDepthMm,2), volume(r.grossVolumeLiters))],[copy.explanation.detailedCurrentVolume,`${number(r.grossVolumeLiters,0)} L`]], formula: state.soilModel?copy.explanation.zoneSpecificGrossFormula:copy.explanation.grossDepthNetDepthEfficiencyLitersDepthArea },
    { title: copy.explanation.planTargetsAndRemainingDelivery, source: copy.explanation.simulatedFlowNominalFallbackWhenUnavailable, rows: [...state.zones.flatMap(z => [[copy.explanation.zonePlanTarget(z.id),volume(z.targetVolumeLiters)],[copy.explanation.zoneRemaining(z.id),`${volume(Math.max(0,z.targetVolumeLiters-z.deliveredVolumeLiters))} · ${duration(zoneRemainingMinutes(z))}`]]),[copy.explanation.totalPlanTarget,volume(planTargetLiters)],[copy.explanation.alreadyDelivered,volume(planDeliveredLiters)],[copy.explanation.remainingPlanDelivery,volume(planRemainingLiters)],[copy.explanation.remainingPumpTime,duration(remainingPumpMinutes)]], formula: copy.explanation.targetsIncludeWaterAlreadyDeliveredAndMayBe },
  ];
  return <Dialog.Root><Dialog.Trigger className={className}>{copy.explanation.whyThisRecommendation}<ArrowUpRight size={13} /></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="drawer"><Dialog.Close className="close-dialog" aria-label={copy.explanation.closeExplanation}><X size={16} /></Dialog.Close><div className="eyebrow">{copy.explanation.theScienceBehindYourPlan}</div><Dialog.Title>{copy.explanation.everyDropExplained}</Dialog.Title><Dialog.Description>{copy.explanation.aTransparentPathFromWeatherAndSoilTo}</Dialog.Description>{steps.map((step,index) => <section className="calculation-step" key={step.title}><h3><span className="step-number">{index+1}</span>{step.title}</h3>{step.rows.map(([label,value]) => <StatRow key={label} label={label} value={value} />)}{step.formula && <div className="formula">{step.formula}</div>}<div className="source-note"><Info size={10} />{step.source}</div></section>)}<p className="fine-print">{copy.explanation.engine}{c.engineVersion} · {brand.methodology}</p></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
