'use client';
import { copy } from '@/config/copy';
import { useRouter } from 'next/navigation';
import { ArrowRight, CalendarDays, CircleCheck, CloudRain, Droplets, Leaf, Lightbulb, Radio, ShieldCheck, Sprout, Sun, TriangleAlert } from 'lucide-react';
import { useProduct } from './product-provider';
import { Badge, Card, CardLink, EmptyBackend, Metric, PageHeading, SectionLink } from './ui';
import { FieldArt } from './field-art';
import { GrowthTimeline } from './growth-timeline';
import { MoistureChart, OutlookChart } from './charts';
import { Explanation } from './explanation';
import { duration, localDate, localTime, number } from '@/lib/format';
export function Today() {
  const { state, beginPreview, preview } = useProduct(); const router = useRouter();
  if (!state) return <EmptyBackend />;
  const r = state.recommendation; const online = state.devices.filter(d=>d.status==='online').length;
  const alerts = state.alerts.filter(a=>a.status==='active').slice(0,2);
  return <>
    <PageHeading eyebrow={copy.today.aGoodDayToGrow} title={copy.today.yourFieldAtAGlance} description={copy.today.aClearPlanForHealthierCropsEveryDrop}><span className="date-pill"><CalendarDays size={13} />{localDate(state.clock,{year:'numeric'})}</span></PageHeading>
    <section className="hero-card"><div className="hero-content"><div className="hero-eyebrow"><span />{copy.today.todaySRecommendation}</div><h2>{r.status==='irrigate'?copy.today.irrigationRecommendedToday:r.title}</h2><p className="hero-copy">{r.reason}</p><div className="hero-metrics"><Metric label={copy.today.grossWaterDelivery} value={number(r.grossVolumeLiters/1000)} unit="m³" hint={copy.today.mNetRootZoneNeed(number(r.netVolumeLiters/1000))} /><Metric label={copy.today.estimatedTimeZone} value={Math.round(r.perZoneRuntimeMinutes)} unit="min" hint={copy.today.text4ZonesTotal(duration(r.estimatedRuntimeMinutes))} /></div><div className="hero-actions"><button className="button light" disabled={r.status==='blocked'||r.grossVolumeLiters<=0} onClick={()=>{if(!preview)beginPreview();router.push('/irrigation');}}>{copy.today.previewIrrigation}<ArrowRight size={14} /></button><Explanation /></div></div><div className="hero-art"><FieldArt dark /><div className="hero-art-label"><Sprout size={12} />{copy.today.potatoMidSeason1Hectare}</div></div></section>
    <div className="grid overview-stats">
      <Card className="overview-stat" title={copy.today.rootZoneWater} icon={Droplets}><div className="stat-main"><strong>{number(state.soil.rootZoneDepletionMm)}</strong><span>{copy.today.mmDepleted}</span></div><div className="mini-track"><span style={{width:`${Math.min(100,state.soil.rootZoneDepletionMm/state.soil.tawMm*100)}%`}} /></div><div className="stat-caption">{copy.today.actionThreshold}{number(state.soil.rawMm)} mm</div></Card>
      <Card className="overview-stat" title={copy.today.todaySWeather} icon={Sun}><div className="weather-value"><div className="stat-main"><strong>{number(state.calculation.meanTemperatureC,0)}°</strong><span>{copy.today.clearSkies}</span></div><Sun className="weather-sun" size={32} strokeWidth={1.4} /></div><p className="stat-caption">{state.weather.temperatureMaxC}° / {state.weather.temperatureMinC}{copy.today.wind}{number(state.weather.windSpeedMps)} m/s</p></Card>
      <Card className="overview-stat" title={copy.today.rainReceived} icon={CloudRain}><div className="rain-stat"><div className="stat-main"><strong>{number(state.rain.observedMm)}</strong><span>mm</span></div><span className="old">{number(state.rain.forecastMm)}</span></div><p className="stat-caption">{number(state.rain.forecastMm)}{copy.today.mmForecast}{state.rain.reconciled?copy.today.windowComplete:copy.today.awaitingRainfallWindow}</p></Card>
      <Card className="overview-stat" title={copy.today.systemHealth} icon={Radio}><div className="status-row"><span className="status-dot" /><strong>{r.confidence==='Complete'?copy.today.readyToIrrigate:r.confidence==='Moderate'?copy.today.someInputsMissing:copy.today.needsAttention}</strong></div><p className="stat-caption">{online}{copy.today.ofCount}{state.devices.length}{copy.today.devicesOnline}</p><div style={{marginTop:8}}><Badge tone={r.confidence==='Complete'?'green':'amber'}><ShieldCheck size={10} />{r.confidence}{copy.today.dataQualitySuffix}</Badge></div></Card>
    </div>
    <div className="grid main-grid section-gap"><Card title={copy.today.theWeekAhead} action={<CardLink href="/forecast">{copy.today.text7DayOutlook}</CardLink>}><p className="card-description">{copy.today.aLittleForesightGoesALongWay}</p><OutlookChart state={state} /></Card><Card title={copy.today.fieldNotes} action={<Badge tone="neutral">{copy.today.latestUpdates}</Badge>}><div className="alert-list">{alerts.length?alerts.map(alert=><div className="alert-item" key={alert.id}><span className={`alert-symbol ${alert.severity==='critical'?'critical':''}`}><TriangleAlert size={16} /></span><div><strong>{alert.title}</strong><p>{alert.message}</p><time>{localTime(alert.detectedAt)} · {localDate(alert.detectedAt)}</time></div></div>):<div className="alert-item"><span className="alert-symbol good"><CircleCheck size={16} /></span><div><strong>{copy.today.yourFieldIsInGoodHands}</strong><p>{copy.today.noActiveAlertsWeLlLetYouKnow}</p></div></div>}<div className="alert-item"><span className="alert-symbol good"><Sprout size={16} /></span><div><strong>{copy.today.growingThrough}{state.field.growthStage.toLowerCase()}</strong><p>{copy.today.day}{state.field.daysAfterPlanting}{copy.today.ofTheConfigured90DaySeasonConsistentRoot}</p></div></div></div><SectionLink href="/history">{copy.today.viewFieldHistory}</SectionLink></Card></div>
    <div className="grid main-grid section-gap"><Card title={copy.today.beneathTheSurface} action={<CardLink href="/field">{copy.today.exploreSoilProfile}</CardLink>}><p className="card-description">{copy.today.soilMoistureAtThreeDepthsVolumetricWaterContent}</p><MoistureChart state={state} /></Card><Card title={copy.today.yourCropGrowingSteadily} icon={Leaf}><div className="eyebrow" style={{marginTop:23}}>{copy.today.potato}{state.field.growthStage.toUpperCase()}</div><div className="stat-main"><strong>{state.field.daysAfterPlanting}</strong><span>{copy.today.daysSincePlanting}</span></div><GrowthTimeline stage={state.field.growthStage} /><p className="stat-caption">{copy.today.planted}{localDate(state.field.plantingDate+'T12:00:00Z')}{copy.today.rootDepth}{state.field.rootDepthM*100} cm</p><SectionLink href="/field">{copy.today.getToKnowYourField}</SectionLink></Card></div>
    <div className="insight-strip"><Lightbulb size={19} /><p><strong>{copy.today.scienceYouCanFollow}</strong>{copy.today.everyRecommendationConnectsWeatherCropGrowthAndThe}</p><Explanation className="text-link" /></div>
  </>;
}
