'use client';
import { useRouter } from 'next/navigation';
import { ArrowRight, CalendarDays, CircleCheck, CloudRain, Droplets, Leaf, Lightbulb, Radio, ShieldCheck, Sprout, Sun, TriangleAlert } from 'lucide-react';
import { useProduct } from './product-provider';
import { Badge, Card, CardLink, EmptyBackend, Metric, PageHeading, SectionLink } from './ui';
import { FieldArt } from './field-art';
import { GrowthTimeline } from './growth-timeline';
import { MoistureChart, OutlookChart } from './charts';
import { Explanation } from './explanation';
import { duration, localDate, localTime, number } from '@/lib/format';
export function Today() {
  const { state, beginPreview, preview } = useProduct(); const router = useRouter();
  if (!state) return <EmptyBackend />;
  const r = state.recommendation; const online = state.devices.filter(d=>d.status==='online').length;
  const alerts = state.alerts.filter(a=>a.status==='active').slice(0,2);
  return <>
    <PageHeading eyebrow="A GOOD DAY TO GROW" title="Your field, at a glance." description="A clear plan for healthier crops. Every drop accounted for."><span className="date-pill"><CalendarDays size={13} />{localDate(state.clock,{year:'numeric'})}</span></PageHeading>
    <section className="hero-card"><div className="hero-content"><div className="hero-eyebrow"><span />TODAY’S RECOMMENDATION</div><h2>{r.status==='irrigate'?'Irrigation recommended today.':r.title}</h2><p className="hero-copy">{r.reason}</p><div className="hero-metrics"><Metric label="Gross water delivery" value={number(r.grossVolumeLiters/1000)} unit="m³" hint={`${number(r.netVolumeLiters/1000)} m³ net root-zone need`} /><Metric label="Estimated time / zone" value={Math.round(r.perZoneRuntimeMinutes)} unit="min" hint={`4 zones · ${duration(r.estimatedRuntimeMinutes)} total`} /></div><div className="hero-actions"><button className="button light" disabled={r.status==='blocked'||r.grossVolumeLiters<=0} onClick={()=>{if(!preview)beginPreview();router.push('/irrigation');}}>Preview irrigation<ArrowRight size={14} /></button><Explanation /></div></div><div className="hero-art"><FieldArt dark /><div className="hero-art-label"><Sprout size={12} />Potato · Mid-season · 1 hectare</div></div></section>
    <div className="grid overview-stats">
      <Card className="overview-stat" title="Root-zone water" icon={Droplets}><div className="stat-main"><strong>{number(state.soil.rootZoneDepletionMm)}</strong><span>mm depleted</span></div><div className="mini-track"><span style={{width:`${Math.min(100,state.soil.rootZoneDepletionMm/state.soil.tawMm*100)}%`}} /></div><div className="stat-caption">Action threshold: {number(state.soil.rawMm)} mm</div></Card>
      <Card className="overview-stat" title="Today’s weather" icon={Sun}><div className="weather-value"><div className="stat-main"><strong>{number(state.calculation.meanTemperatureC,0)}°</strong><span>Clear skies</span></div><Sun className="weather-sun" size={32} strokeWidth={1.4} /></div><p className="stat-caption">{state.weather.temperatureMaxC}° / {state.weather.temperatureMinC}° · Wind {number(state.weather.windSpeedMps)} m/s</p></Card>
      <Card className="overview-stat" title="Rain received" icon={CloudRain}><div className="rain-stat"><div className="stat-main"><strong>{number(state.rain.observedMm)}</strong><span>mm</span></div><span className="old">{number(state.rain.forecastMm)}</span></div><p className="stat-caption">{number(state.rain.forecastMm)} mm forecast · {state.rain.reconciled?'Window complete':'Awaiting rainfall window'}</p></Card>
      <Card className="overview-stat" title="System health" icon={Radio}><div className="status-row"><span className="status-dot" /><strong>{r.confidence==='Complete'?'Ready to irrigate':r.confidence==='Moderate'?'Some inputs missing':'Needs attention'}</strong></div><p className="stat-caption">{online} of {state.devices.length} devices online</p><div style={{marginTop:8}}><Badge tone={r.confidence==='Complete'?'green':'amber'}><ShieldCheck size={10} />{r.confidence} data</Badge></div></Card>
    </div>
    <div className="grid main-grid section-gap"><Card title="The week ahead" action={<CardLink href="/forecast">7-day outlook</CardLink>}><p className="card-description">A little foresight goes a long way.</p><OutlookChart state={state} /></Card><Card title="Field notes" action={<Badge tone="neutral">Latest updates</Badge>}><div className="alert-list">{alerts.length?alerts.map(alert=><div className="alert-item" key={alert.id}><span className={`alert-symbol ${alert.severity==='critical'?'critical':''}`}><TriangleAlert size={16} /></span><div><strong>{alert.title}</strong><p>{alert.message}</p><time>{localTime(alert.detectedAt)} · {localDate(alert.detectedAt)}</time></div></div>):<div className="alert-item"><span className="alert-symbol good"><CircleCheck size={16} /></span><div><strong>Your field is in good hands.</strong><p>No active alerts. We’ll let you know when something needs attention.</p></div></div>}<div className="alert-item"><span className="alert-symbol good"><Sprout size={16} /></span><div><strong>Growing through {state.field.growthStage.toLowerCase()}</strong><p>Day {state.field.daysAfterPlanting} of the configured 90-day season. Consistent root-zone moisture matters.</p></div></div></div><SectionLink href="/history">View field history</SectionLink></Card></div>
    <div className="grid main-grid section-gap"><Card title="Beneath the surface" action={<CardLink href="/field">Explore soil profile</CardLink>}><p className="card-description">Soil moisture at three depths · volumetric water content</p><MoistureChart state={state} /></Card><Card title="Your crop, growing steadily" icon={Leaf}><div className="eyebrow" style={{marginTop:23}}>POTATO · {state.field.growthStage.toUpperCase()}</div><div className="stat-main"><strong>{state.field.daysAfterPlanting}</strong><span>days since planting</span></div><GrowthTimeline stage={state.field.growthStage} /><p className="stat-caption">Planted {localDate(state.field.plantingDate+'T12:00:00Z')} · Root depth {state.field.rootDepthM*100} cm</p><SectionLink href="/field">Get to know your field</SectionLink></Card></div>
    <div className="insight-strip"><Lightbulb size={19} /><p><strong>Science you can follow.</strong> Every recommendation connects weather, crop growth, and the water in your soil.</p><Explanation className="text-link" /></div>
  </>;
}
