'use client';
import { useCopy } from '@/config/locale-copy';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Database, RefreshCw, type LucideIcon } from 'lucide-react';
import { useProduct } from './product-provider';
export function PageHeading({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><div className="page-heading-actions">{children}</div></div>; }
export function Card({ title, eyebrow, icon: Icon, action, children, className = '' }: { title?: string; eyebrow?: string; icon?: LucideIcon; action?: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}><div className="card-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}{title && <h2>{Icon && <Icon size={17} />}{title}</h2>}</div>{action}</div>{children}</section>; }
export function CardLink({ href, children }: { href: string; children?: React.ReactNode }) { const copy = useCopy(); return <Link className="text-link" href={href}>{children ?? copy.ui.viewDetails}<ArrowUpRight size={14} /></Link>; }
export function Badge({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'blue' | 'neutral' | 'red' }) { return <span className={`badge ${tone}`}>{children}</span>; }
export function Metric({ label, value, unit, hint }: { label: string; value: React.ReactNode; unit?: string; hint?: string }) { return <div className="metric"><span>{label}</span><strong>{value}{unit && <small>{unit}</small>}</strong>{hint && <p>{hint}</p>}</div>; }
export function EmptyBackend() {const copy = useCopy(); const { error, refresh } = useProduct(); return <div className="unavailable"><span className="unavailable-icon"><Database size={32} /></span><div className="eyebrow">{copy.ui.fieldConnection}</div><h1>{copy.ui.letSConnectYourField}</h1><p>{error || copy.ui.theFieldDatabaseIsCurrentlyUnavailable}</p><p className="muted">{copy.ui.theApplicationWillShowYourSavedFieldState}</p><button className="button primary" onClick={() => void refresh()}><RefreshCw size={16} />{copy.ui.retryConnection}</button></div>; }
export function StatRow({ label, value }: { label: string; value: React.ReactNode }) { return <div className="stat-row"><span>{label}</span><strong>{value}</strong></div>; }
export function SectionLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link className="section-link" href={href}>{children}<ArrowRight size={16} /></Link>; }
